# Generated by Django 5.2.15 on 2026-07-13 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('egg', 'Egg'), ('tray', 'Tray')], default='egg', max_length=10)),
                ('grade', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('collection_start_date', models.DateField()),
                ('collection_end_date', models.DateField()),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_inventory', to='organization_branch.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_egg',
            },
        ),
    ]
