# Generated by Django 5.2.15 on 2026-07-15 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('inventory_egg', '0001_initial'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='egginventory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'branch'), name='unique_active_egg_inventory_per_branch'),
        ),
    ]
