# Generated by Django 5.2.15 on 2026-08-12 16:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0007_alter_tenant_logo'),
        ('inventory_egg', '0002_egginventory_unique_active_egg_inventory_per_branch'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.CharField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium'), ('SMALL', 'Small'), ('PULLET', 'Pullet'), ('UNSORTED', 'Unsorted')], max_length=20)),
                ('movement_type', models.CharField(choices=[('production', 'Production'), ('production_reversal', 'Production Reversal'), ('invoice_sale', 'Invoice Sale'), ('invoice_sale_reversal', 'Invoice Sale Reversal'), ('adjustment', 'Adjustment')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('piece', 'Piece')], default='piece', max_length=10)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Egg Stock Movement',
                'verbose_name_plural': 'Egg Stock Movements',
                'db_table': 'egg_stock_movement',
            },
        ),
        migrations.RemoveConstraint(
            model_name='egginventory',
            name='unique_active_egg_inventory_per_branch',
        ),
        migrations.AlterField(
            model_name='egginventory',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='egginventory',
            name='grade',
            field=models.CharField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium'), ('SMALL', 'Small'), ('PULLET', 'Pullet'), ('UNSORTED', 'Unsorted')], default='UNSORTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='egginventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='egginventory',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece')], default='piece', max_length=10),
        ),
        migrations.AddIndex(
            model_name='egginventory',
            index=models.Index(fields=['tenant', 'branch', 'grade'], name='idx_egginv_tenant_branch_grade'),
        ),
        migrations.AddConstraint(
            model_name='egginventory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'branch', 'grade'), name='unique_active_egg_inventory_per_branch_grade'),
        ),
        migrations.AddField(
            model_name='eggstockmovement',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_stock_movements', to='organization_branch.branch'),
        ),
        migrations.AddField(
            model_name='eggstockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eggstockmovement',
            name='egg_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory_egg.egginventory'),
        ),
        migrations.AddField(
            model_name='eggstockmovement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='eggstockmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eggstockmovement',
            index=models.Index(fields=['tenant', 'branch', 'grade', 'created_at'], name='idx_eggmv_tenant_branch_grade'),
        ),
        migrations.AddIndex(
            model_name='eggstockmovement',
            index=models.Index(fields=['tenant', 'reference_id'], name='idx_eggmv_tenant_reference'),
        ),
    ]
