# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bird_type', models.CharField(choices=[('layer', 'Layer'), ('broiler', 'Broiler'), ('both', 'Both')], max_length=20)),
                ('disease_type', models.CharField(max_length=30)),
                ('symptoms', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'db_table': 'health_disease',
                'indexes': [models.Index(fields=['tenant', 'bird_type'], name='idx_disease_tenant_birdtype')],
            },
        ),
    ]
