# Generated by Django 5.2.15 on 2026-07-11 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('health_disease', '0002_disease_created_by_disease_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease_type',
            field=models.CharField(choices=[('viral', 'Viral'), ('bacterial', 'Bacterial'), ('parasitic', 'Parasitic'), ('fungal', 'Fungal'), ('nutritional', 'Nutritional'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='disease',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_disease_per_tenant'),
        ),
    ]
