# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('livestock_batch', '0001_initial'),
        ('organization_branch', '0001_initial'),
        ('organization_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDailyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_date', models.DateField()),
                ('opening_quantity', models.IntegerField()),
                ('deaths', models.IntegerField(default=0)),
                ('culls', models.IntegerField(default=0)),
                ('closing_quantity', models.IntegerField()),
                ('feed_consumed_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_consumed_l', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock_batch.birdbatch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_branch.branch')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_house.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Batch Daily Record',
                'verbose_name_plural': 'Batch Daily Records',
                'db_table': 'livestock_batchdailyrecord',
                'indexes': [models.Index(fields=['tenant', 'batch', 'record_date'], name='idx_dailyrec_tenant_batch_date'), models.Index(fields=['tenant', 'branch', 'record_date'], name='idx_dailyrec_tnt_branch_date')],
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock_batch.birdbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Mortality Record',
                'verbose_name_plural': 'Mortality Records',
                'db_table': 'livestock_mortalityrecord',
                'indexes': [models.Index(fields=['tenant', 'batch', 'date'], name='idx_mortality_tnt_batch_date')],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('average_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_size', models.IntegerField(default=10)),
                ('date', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock_batch.birdbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Weight Record',
                'verbose_name_plural': 'Weight Records',
                'db_table': 'livestock_weightrecord',
                'indexes': [models.Index(fields=['tenant', 'batch', 'date'], name='idx_weight_tenant_batch_date')],
            },
        ),
    ]
