# Generated by Django 5.2.15 on 2026-07-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock_lifecycle', '0002_batchdailyrecord_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MortalityRecord',
        ),
    ]
