# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('health_outbreak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('birds_recovered', models.IntegerField()),
                ('birds_dead', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('outbreak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_outbreak.diseaseoutbreak')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Recovery Record',
                'verbose_name_plural': 'Recovery Records',
                'db_table': 'health_recoveryrecord',
                'indexes': [models.Index(fields=['tenant', 'outbreak', 'date'], name='idx_recovery_tnt_outbreak_date')],
            },
        ),
    ]
