# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('livestock_breed', '0001_initial'),
        ('organization_branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'livestock_supplier',
            },
        ),
        migrations.CreateModel(
            name='ChickPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_date', models.DateField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_branch.branch')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock_breed.breed')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock_purchase.supplier')),
            ],
            options={
                'verbose_name': 'Chick Purchase',
                'verbose_name_plural': 'Chick Purchases',
                'db_table': 'livestock_chickpurchase',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'livestock_customer',
                'indexes': [models.Index(fields=['tenant'], name='idx_customer_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant'], name='idx_supplier_tenant'),
        ),
        migrations.AddIndex(
            model_name='chickpurchase',
            index=models.Index(fields=['tenant', 'branch'], name='idx_chickpur_tenant_branch'),
        ),
        migrations.AddIndex(
            model_name='chickpurchase',
            index=models.Index(fields=['tenant', 'purchase_date'], name='idx_chickpur_tenant_date'),
        ),
    ]
