# Generated by Django 5.2.15 on 2026-07-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock_breed', '0001_initial'),
        ('livestock_purchase', '0001_initial'),
        ('organization_branch', '0002_branch_unique_branch_name_per_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickpurchase',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chick_purchases', to='organization_branch.branch'),
        ),
        migrations.AlterField(
            model_name='chickpurchase',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chick_purchases', to='livestock_breed.breed'),
        ),
        migrations.AlterField(
            model_name='chickpurchase',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chickpurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chick_purchases', to='livestock_purchase.supplier'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
