# Generated by Django 5.2.15 on 2026-07-11 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('feed_feed_type', '0002_feedtype_description'),
        ('livestock_purchase', '0002_alter_chickpurchase_branch_alter_chickpurchase_breed_and_more'),
        ('organization_branch', '0002_branch_unique_branch_name_per_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_date', models.DateField()),
                ('quantity_bags', models.PositiveIntegerField()),
                ('weight_per_bag', models.DecimalField(decimal_places=2, help_text='Weight of each bag in kg', max_digits=6)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per bag', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_purchases', to='organization_branch.branch')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='feed_feed_type.feedtype')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_purchases', to='livestock_purchase.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Feed Purchase',
                'verbose_name_plural': 'Feed Purchases',
                'db_table': 'feed_feedpurchase',
                'indexes': [models.Index(fields=['tenant', 'branch'], name='idx_feedpur_tenant_branch'), models.Index(fields=['tenant', 'purchase_date'], name='idx_feedpur_tenant_date')],
            },
        ),
    ]
