# Generated by Django 5.2.15 on 2026-08-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock_batch', '0004_alter_birdbatch_breed_and_more'),
        ('livestock_purchase', '0004_chickpurchase_created_by_chickpurchase_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickpurchase',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chick_purchase', to='livestock_batch.birdbatch'),
        ),
    ]
