# Generated by Django 5.2.15 on 2026-08-12 16:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0002_invoice_branch_invoice_due_date_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('bird', 'Bird'), ('kg', 'Kilogram'), ('piece', 'Piece'), ('crate', 'Crate'), ('egg', 'Egg'), ('tray', 'Tray')], default='bird', max_length=20),
        ),
    ]
