# Generated by Django 5.2.15 on 2026-07-13 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('health_disease', '0003_disease_description_alter_disease_disease_type_and_more'),
        ('health_outbreak', '0003_alter_diseaseoutbreak_batch_and_more'),
        ('livestock_batch', '0003_birdbatch_created_by_birdbatch_updated_by'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('organization_house', '0003_house_created_by_house_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('cause', models.CharField(choices=[('disease', 'Disease'), ('heat_stress', 'Heat Stress'), ('accident', 'Accident'), ('predator', 'Predator'), ('poor_quality', 'Poor Chick Quality'), ('unknown', 'Unknown'), ('other', 'Other')], default='unknown', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalities', to='livestock_batch.birdbatch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalities', to='organization_branch.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortalities', to='health_disease.disease')),
                ('disease_outbreak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortalities', to='health_outbreak.diseaseoutbreak')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalities', to='organization_house.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mortality',
                'verbose_name_plural': 'Mortalities',
                'db_table': 'livestock_mortality',
                'indexes': [models.Index(fields=['tenant', 'batch', 'date'], name='idx_mortality_tnt_batch_date'), models.Index(fields=['tenant', 'branch', 'date'], name='idx_mortality_tnt_branch_date')],
            },
        ),
    ]
