# Generated by Django 5.2.15 on 2026-08-16 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0007_alter_tenant_logo'),
        ('finance_invoice', '0003_invoiceitem_stock_quantity_alter_invoiceitem_unit'),
        ('finance_payment', '0002_alter_payment_options_payment_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_purpose',
            field=models.CharField(choices=[('invoice_payment', 'Invoice Payment'), ('expense_payment', 'Expense Payment'), ('supplier_payment', 'Supplier Payment'), ('other', 'Other')], default='invoice_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance_invoice.invoice'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_purpose'], name='idx_payment_tenant_purpose'),
        ),
    ]
