# Generated by Django 5.2.15 on 2026-07-05 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFarmAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('total_birds', models.IntegerField()),
                ('mortality', models.IntegerField()),
                ('feed_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egg_production', models.IntegerField(default=0)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Daily Farm Analytics',
                'verbose_name_plural': 'Daily Farm Analytics',
                'db_table': 'analytics_dailyfarmanalytics',
            },
        ),
    ]
