# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_daily_farm_analytics', '0001_initial'),
        ('core_tenant', '0001_initial'),
        ('organization_branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfarmanalytics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_branch.branch'),
        ),
        migrations.AddField(
            model_name='dailyfarmanalytics',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant'),
        ),
        migrations.AddIndex(
            model_name='dailyfarmanalytics',
            index=models.Index(fields=['tenant', 'branch', 'date'], name='idx_dfa_tenant_branch_date'),
        ),
    ]
