# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('organization_branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('house_type', models.CharField(choices=[('deep_litter', 'Deep Litter'), ('cage', 'Cage')], max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_branch.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'db_table': 'organization_house',
                'indexes': [models.Index(fields=['tenant', 'branch'], name='idx_house_tenant_branch')],
            },
        ),
    ]
