# Generated by Django 5.2.15 on 2026-07-10 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('organization_branch', '0002_branch_unique_branch_name_per_tenant'),
        ('organization_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='organization_branch.branch'),
        ),
        migrations.AlterField(
            model_name='house',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_house_name_per_branch'),
        ),
    ]
