# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('feed_feed_type', '0001_initial'),
        ('livestock_batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock_batch.birdbatch')),
                ('feed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed_feed_type.feedtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Feed Consumption',
                'verbose_name_plural': 'Feed Consumptions',
                'db_table': 'feed_consumption',
                'indexes': [models.Index(fields=['tenant', 'batch', 'date'], name='idx_feedcons_tenant_batch_date')],
            },
        ),
    ]
