# Generated by Copilot on 2026-08-11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_feed_consumption_branch_and_house(apps, schema_editor):
    FeedConsumption = apps.get_model(
        "feed_consumption",
        "FeedConsumption",
    )

    for consumption in FeedConsumption.objects.select_related(
        "batch"
    ):
        updates = []

        if (
            consumption.batch_id
            and consumption.branch_id is None
        ):
            consumption.branch_id = (
                consumption.batch.branch_id
            )
            updates.append("branch")

        if (
            consumption.batch_id
            and consumption.house_id is None
        ):
            consumption.house_id = (
                consumption.batch.house_id
            )
            updates.append("house")

        if updates:
            consumption.save(
                update_fields=updates
            )


class Migration(migrations.Migration):

    dependencies = [
        ("feed_consumption", "0002_feedconsumption_created_by_and_more"),
        ("feed_feed_type", "0003_feedtype_created_by_feedtype_updated_by"),
        ("livestock_batch", "0006_alter_birdbatch_house"),
        ("organization_branch", "0003_branch_created_by_branch_updated_by"),
        ("organization_house", "0003_house_created_by_house_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedconsumption",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_consumptions",
                to="organization_branch.branch",
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_consumptions",
                to="organization_house.house",
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="unit",
            field=models.CharField(
                choices=[("kg", "Kilogram")],
                default="kg",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="feedconsumption",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_consumptions",
                to="livestock_batch.birdbatch",
            ),
        ),
        migrations.AlterField(
            model_name="feedconsumption",
            name="feed_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feed_consumptions",
                to="feed_feed_type.feedtype",
            ),
        ),
        migrations.AlterField(
            model_name="feedconsumption",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
            ),
        ),
        migrations.RunPython(
            populate_feed_consumption_branch_and_house,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="feedconsumption",
            index=models.Index(
                fields=["tenant", "branch", "date"],
                name="idx_feedcons_tenant_branch_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedconsumption",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("quantity__gt", 0)
                ),
                name="feed_consumption_quantity_positive",
            ),
        ),
        migrations.CreateModel(
            name="FeedInventory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("available_quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("unit", models.CharField(choices=[("kg", "Kilogram")], default="kg", max_length=10)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feed_inventories", to="organization_branch.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("feed_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="feed_inventories", to="feed_feed_type.feedtype")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core_tenant.tenant")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Feed Inventory",
                "verbose_name_plural": "Feed Inventory",
                "db_table": "feed_inventory",
                "indexes": [
                    models.Index(
                        fields=["tenant", "branch", "feed_type"],
                        name="idx_feedinv_tenant_branch_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedStockMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("movement_type", models.CharField(choices=[("purchase", "Purchase"), ("purchase_reversal", "Purchase Reversal"), ("consumption", "Consumption"), ("consumption_reversal", "Consumption Reversal"), ("adjustment", "Adjustment")], max_length=30)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(choices=[("kg", "Kilogram")], default="kg", max_length=10)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feed_stock_movements", to="organization_branch.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("feed_inventory", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movements", to="feed_consumption.feedinventory")),
                ("feed_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="feed_feed_type.feedtype")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core_tenant.tenant")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Feed Stock Movement",
                "verbose_name_plural": "Feed Stock Movements",
                "db_table": "feed_stock_movement",
                "indexes": [
                    models.Index(
                        fields=["tenant", "branch", "feed_type", "created_at"],
                        name="idx_feedmove_tnt_branch_type_created",
                    ),
                    models.Index(
                        fields=["tenant", "reference_id"],
                        name="idx_feedmove_tenant_reference",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="feedinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True)
                ),
                fields=("tenant", "branch", "feed_type"),
                name="uniq_active_feed_inventory_per_branch_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedinventory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("quantity__gte", 0)
                ),
                name="feed_inventory_quantity_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedinventory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("available_quantity__gte", 0)
                ),
                name="feed_inventory_available_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedinventory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("available_quantity__lte", models.F("quantity"))
                ),
                name="feed_inventory_available_not_more_than_quantity",
            ),
        ),
    ]
