# Generated by Django 5.2.15 on 2026-08-11 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0007_alter_tenant_logo'),
        ('feed_consumption', '0003_feedinventory_feedstockmovement_and_more'),
        ('feed_feed_type', '0003_feedtype_created_by_feedtype_updated_by'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedinventory',
            name='uniq_active_feed_inventory_per_branch_type',
        ),
        migrations.RemoveConstraint(
            model_name='feedinventory',
            name='feed_inventory_quantity_not_negative',
        ),
        migrations.RemoveConstraint(
            model_name='feedinventory',
            name='feed_inventory_available_not_negative',
        ),
        migrations.RemoveConstraint(
            model_name='feedinventory',
            name='feed_inventory_available_not_more_than_quantity',
        ),
        migrations.RenameIndex(
            model_name='feedconsumption',
            new_name='idx_feedcons_tnt_branch_date',
            old_name='idx_feedcons_tenant_branch_date',
        ),
        migrations.RenameIndex(
            model_name='feedstockmovement',
            new_name='idx_feedmv_tnt_branch_type_c',
            old_name='idx_feedmove_tnt_branch_type_created',
        ),
        migrations.AlterField(
            model_name='feedconsumption',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='feedinventory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'branch', 'feed_type'), name='uniq_active_feed_inv_per_branch_type'),
        ),
        migrations.AddConstraint(
            model_name='feedinventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='feed_inv_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='feedinventory',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0)), name='feed_inv_available_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='feedinventory',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__lte', models.F('quantity'))), name='feed_inv_available_not_more_than_quantity'),
        ),
    ]
