# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('livestock_breed', '0001_initial'),
        ('livestock_purchase', '0001_initial'),
        ('organization_branch', '0001_initial'),
        ('organization_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('bird_type', models.CharField(max_length=20)),
                ('arrival_date', models.DateField()),
                ('initial_quantity', models.IntegerField()),
                ('current_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('sold', 'Sold')], default='active', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_branch.branch')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock_breed.breed')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_house.house')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock_purchase.chickpurchase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Bird Batch',
                'verbose_name_plural': 'Bird Batches',
                'db_table': 'livestock_birdbatch',
                'indexes': [models.Index(fields=['tenant', 'branch'], name='idx_birdbatch_tenant_branch'), models.Index(fields=['tenant', 'status'], name='idx_birdbatch_tenant_status'), models.Index(fields=['tenant', 'batch_number'], name='idx_birdbatch_tenant_batchno')],
            },
        ),
    ]
