# Generated by Django 5.2.15 on 2026-07-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock_batch', '0001_initial'),
        ('organization_branch', '0002_branch_unique_branch_name_per_tenant'),
        ('organization_house', '0002_alter_house_branch_alter_house_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdbatch',
            name='bird_type',
            field=models.CharField(choices=[('layer', 'Layer'), ('broiler', 'Broiler'), ('cockerel', 'Cockerel'), ('breeder', 'Breeder'), ('pullet', 'Pullet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='organization_branch.branch'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='current_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='organization_house.house'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='initial_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
