# Generated by Django 5.2.15 on 2026-07-13 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('livestock_batch', '0003_birdbatch_created_by_birdbatch_updated_by'),
        ('livestock_breed', '0002_breed_created_by_breed_updated_by'),
        ('livestock_purchase', '0004_chickpurchase_created_by_chickpurchase_updated_by_and_more'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('organization_house', '0003_house_created_by_house_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdbatch',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock_breed.breed'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock_purchase.chickpurchase'),
        ),
        migrations.AddConstraint(
            model_name='birdbatch',
            constraint=models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='birdbatch_current_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='birdbatch',
            constraint=models.CheckConstraint(condition=models.Q(('current_quantity__lte', models.F('initial_quantity'))), name='birdbatch_current_not_more_than_initial'),
        ),
    ]
