# Generated by Django 5.2.15 on 2026-08-10 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0007_alter_tenant_logo'),
        ('livestock_batch', '0004_alter_birdbatch_breed_and_more'),
        ('livestock_breed', '0002_breed_created_by_breed_updated_by'),
        ('livestock_purchase', '0005_chickpurchase_batch'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('organization_house', '0003_house_created_by_house_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdbatch',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='livestock_breed.breed'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='organization_house.house'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='livestock_purchase.chickpurchase'),
        ),
        migrations.AddIndex(
            model_name='birdbatch',
            index=models.Index(fields=['tenant', 'branch', 'house'], name='idx_batch_tenant_branch_house'),
        ),
        migrations.AddConstraint(
            model_name='birdbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'house', 'batch_number'), name='uniq_birdbatch_tenant_branch_house_number'),
        ),
        migrations.AddConstraint(
            model_name='birdbatch',
            constraint=models.CheckConstraint(condition=models.Q(('initial_quantity__gt', 0)), name='birdbatch_initial_quantity_positive'),
        ),
    ]
