# Generated by Django 5.2.15 on 2026-08-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock_batch', '0005_alter_birdbatch_breed_alter_birdbatch_house_and_more'),
        ('organization_house', '0003_house_created_by_house_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdbatch',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='organization_house.house'),
        ),
    ]
