# Generated by Django 5.2.15 on 2026-07-13 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('livestock_batch', '0004_alter_birdbatch_breed_and_more'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('production_harvest', '0002_harvest_created_by_harvest_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='harvest',
            name='idx_harvest_tenant_batch_date',
        ),
        migrations.RemoveIndex(
            model_name='harvest',
            name='idx_harvest_tenant_branch_date',
        ),
        migrations.RenameField(
            model_name='harvest',
            old_name='date',
            new_name='harvest_date',
        ),
        migrations.AddField(
            model_name='harvest',
            name='harvest_reason',
            field=models.CharField(choices=[('sale', 'Sale'), ('processing', 'Processing'), ('consumption', 'Farm Consumption'), ('culling', 'Culling'), ('other', 'Other')], default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='harvest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='average_weight',
            field=models.DecimalField(decimal_places=2, help_text='Average weight per bird (kg)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='livestock_batch.birdbatch'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='birds_harvested',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='organization_branch.branch'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total harvested weight (kg)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['tenant', 'batch', 'harvest_date'], name='idx_harvest_tenant_batch_date'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['tenant', 'branch', 'harvest_date'], name='idx_harvest_tenant_branch_date'),
        ),
    ]
