# Generated by Django 5.2.15 on 2026-07-13 20:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_harvest', '0003_remove_harvest_idx_harvest_tenant_batch_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-harvest_date']},
        ),
        migrations.RenameIndex(
            model_name='harvest',
            new_name='idx_harvest_batch_date',
            old_name='idx_harvest_tenant_batch_date',
        ),
        migrations.RenameIndex(
            model_name='harvest',
            new_name='idx_harvest_branch_date',
            old_name='idx_harvest_tenant_branch_date',
        ),
        migrations.AddField(
            model_name='harvest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_sold', 'Partially Sold'), ('sold', 'Sold'), ('processed', 'Processed'), ('stored', 'Stored'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='average_weight',
            field=models.DecimalField(decimal_places=2, help_text='Average weight per bird in KG', max_digits=8),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total harvested weight in KG', max_digits=10),
        ),
    ]
