# Generated by Django 5.2.15 on 2026-07-13 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('production_harvest', '0004_alter_harvest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='organization_branch.branch'),
        ),
    ]
