# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('health_disease', '0001_initial'),
        ('livestock_batch', '0001_initial'),
        ('organization_branch', '0001_initial'),
        ('organization_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseOutbreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('outbreak_date', models.DateField()),
                ('birds_affected', models.IntegerField()),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock_batch.birdbatch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_branch.branch')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_disease.disease')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_house.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Disease Outbreak',
                'verbose_name_plural': 'Disease Outbreaks',
                'db_table': 'health_diseaseoutbreak',
                'indexes': [models.Index(fields=['tenant', 'batch', 'outbreak_date'], name='idx_outbreak_tenant_batch_date'), models.Index(fields=['tenant', 'branch', 'status'], name='idx_outbreak_tnt_branch_status')],
            },
        ),
    ]
