# Generated by Django 5.2.15 on 2026-07-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_disease', '0003_disease_description_alter_disease_disease_type_and_more'),
        ('health_outbreak', '0002_diseaseoutbreak_created_by_and_more'),
        ('livestock_batch', '0003_birdbatch_created_by_birdbatch_updated_by'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('organization_house', '0003_house_created_by_house_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseoutbreak',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_outbreaks', to='livestock_batch.birdbatch'),
        ),
        migrations.AlterField(
            model_name='diseaseoutbreak',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_outbreaks', to='organization_branch.branch'),
        ),
        migrations.AlterField(
            model_name='diseaseoutbreak',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbreaks', to='health_disease.disease'),
        ),
        migrations.AlterField(
            model_name='diseaseoutbreak',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_outbreaks', to='organization_house.house'),
        ),
        migrations.AlterField(
            model_name='diseaseoutbreak',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='diseaseoutbreak',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('monitoring', 'Monitoring')], default='active', max_length=20),
        ),
    ]
