# Generated by Django 5.2.15 on 2026-07-11 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('health_treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('medication_type', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('vaccine', 'Vaccine'), ('vitamin', 'Vitamin'), ('supplement', 'Supplement'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('unit', models.CharField(choices=[('bottle', 'Bottle'), ('sachet', 'Sachet'), ('tablet', 'Tablet'), ('dose', 'Dose'), ('kg', 'Kg'), ('liter', 'Liter')], default='bottle', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'health_medication',
                'indexes': [models.Index(fields=['tenant', 'medication_type'], name='idx_medication_tenant_type')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_medication_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=50)),
                ('administered_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_treatment.treatmentplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication Administration',
                'verbose_name_plural': 'Medication Administrations',
                'db_table': 'health_medicationadministration',
                'indexes': [models.Index(fields=['tenant', 'treatment'], name='idx_med_tenant_treatment')],
            },
        ),
    ]
