# Generated by Django 5.2.15 on 2026-07-12 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_medication', '0001_initial'),
        ('health_treatment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicationadministration',
            new_name='idx_medadmin_tenant_treatment',
            old_name='idx_med_tenant_treatment',
        ),
        migrations.RemoveField(
            model_name='medicationadministration',
            name='medication_name',
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='medication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='health_medication.medication'),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='route',
            field=models.CharField(choices=[('water', 'Drinking Water'), ('feed', 'Feed'), ('injection', 'Injection'), ('oral', 'Oral'), ('other', 'Other')], default='water', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='health_treatment.treatmentplan'),
        ),
    ]
