# Generated by Django 5.2.15 on 2026-07-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_medication', '0002_rename_idx_med_tenant_treatment_idx_medadmin_tenant_treatment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationadministration',
            old_name='administered_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of days medication should be administered'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='frequency_per_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of times medication is given per day'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='health_medication.medication'),
        ),
    ]
