# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('bird_type', models.CharField(choices=[('layer', 'Layer'), ('broiler', 'Broiler'), ('both', 'Both')], default='both', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Feed Type',
                'verbose_name_plural': 'Feed Types',
                'db_table': 'feed_feedtype',
                'indexes': [models.Index(fields=['tenant'], name='idx_feedtype_tenant')],
            },
        ),
    ]
