# Generated by Django 5.2.15 on 2026-07-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_feed_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
