# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('livestock_batch', '0001_initial'),
        ('organization_branch', '0001_initial'),
        ('organization_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('good_eggs', models.IntegerField(default=0)),
                ('broken_eggs', models.IntegerField(default=0)),
                ('cracked_eggs', models.IntegerField(default=0)),
                ('dirty_eggs', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock_batch.birdbatch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_branch.branch')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_house.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Egg Production',
                'verbose_name_plural': 'Egg Productions',
                'db_table': 'production_eggproduction',
                'indexes': [models.Index(fields=['tenant', 'batch', 'date'], name='idx_eggprod_tenant_batch_date'), models.Index(fields=['tenant', 'branch', 'date'], name='idx_eggprod_tenant_branch_date')],
            },
        ),
    ]
