# Generated by Django 5.2.15 on 2026-07-13 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('livestock_batch', '0003_birdbatch_created_by_birdbatch_updated_by'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('organization_house', '0003_house_created_by_house_updated_by'),
        ('production_egg', '0002_eggproduction_created_by_eggproduction_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eggproduction',
            options={'ordering': ['-production_date'], 'verbose_name': 'Egg Production', 'verbose_name_plural': 'Egg Productions'},
        ),
        migrations.RemoveIndex(
            model_name='eggproduction',
            name='idx_eggprod_tenant_batch_date',
        ),
        migrations.RemoveIndex(
            model_name='eggproduction',
            name='idx_eggprod_tenant_branch_date',
        ),
        migrations.RenameField(
            model_name='eggproduction',
            old_name='date',
            new_name='production_date',
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='double_yolk_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='small_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggproduction',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='livestock_batch.birdbatch'),
        ),
        migrations.AlterField(
            model_name='eggproduction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='organization_branch.branch'),
        ),
        migrations.AlterField(
            model_name='eggproduction',
            name='broken_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggproduction',
            name='cracked_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggproduction',
            name='dirty_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggproduction',
            name='good_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggproduction',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='organization_house.house'),
        ),
        migrations.AddIndex(
            model_name='eggproduction',
            index=models.Index(fields=['tenant', 'batch', 'production_date'], name='idx_eggprod_tenant_batch_date'),
        ),
        migrations.AddIndex(
            model_name='eggproduction',
            index=models.Index(fields=['tenant', 'branch', 'production_date'], name='idx_eggprod_tenant_branch_date'),
        ),
        migrations.AddConstraint(
            model_name='eggproduction',
            constraint=models.UniqueConstraint(fields=('tenant', 'batch', 'production_date'), name='uniq_eggproduction_batch_date'),
        ),
    ]
