# Generated by Django 5.2.15 on 2026-07-15 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('livestock_batch', '0004_alter_birdbatch_breed_and_more'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('organization_house', '0003_house_created_by_house_updated_by'),
        ('production_egg', '0003_alter_eggproduction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eggproduction',
            name='uniq_eggproduction_batch_date',
        ),
        migrations.AddConstraint(
            model_name='eggproduction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'batch', 'production_date'), name='uniq_eggproduction_batch_date'),
        ),
    ]
