# Generated by Django 5.2.15 on 2026-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_egg', '0004_remove_eggproduction_uniq_eggproduction_batch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggproduction',
            name='large_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='medium_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='pullet_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggproduction',
            name='unsorted_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
