# Generated by Django 5.2.15 on 2026-08-16 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0007_alter_tenant_logo'),
        ('finance_expense', '0001_initial'),
        ('finance_payment', '0003_payment_payment_purpose_alter_payment_invoice_and_more'),
        ('livestock_batch', '0006_alter_birdbatch_house'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('organization_house', '0003_house_created_by_house_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='uniq_expense_category_tenant_name',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='tenant',
        ),
        migrations.AddField(
            model_name='expense',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='livestock_batch.birdbatch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='organization_house.house'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'branch'], name='idx_expense_tenant_branch'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'house'], name='idx_expense_tenant_house'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'batch'], name='idx_expense_tenant_batch'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_expense_category_name'),
        ),
    ]
