# Generated by Django 5.2.15 on 2026-08-08 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_authtntuser', '0003_permission_created_by_permission_updated_by_and_more'),
        ('core_tenant', '0006_finalize_tenantuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('tenant', 'module', 'action'), name='unique_tenant_permission'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('tenant', 'role', 'permission'), name='unique_tenant_role_permission'),
        ),
    ]
