# Generated by Django 5.2.15 on 2026-08-08 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_authtntuser', '0004_permission_unique_tenant_permission_and_more'),
        ('core_tenant', '0006_finalize_tenantuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_role_name'),
        ),
    ]
