# Generated by Django 5.2.15 on 2026-07-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('organization_branch', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_branch_name_per_tenant'),
        ),
    ]
