# Generated by Django 5.2.15 on 2026-07-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_disease', '0003_disease_description_alter_disease_disease_type_and_more'),
        ('health_treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='health_disease.disease'),
        ),
    ]
