# Generated by Django 5.2.15 on 2026-07-07 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'verbose_name': 'Tenant User', 'verbose_name_plural': 'Tenant Users'},
        ),
        migrations.RenameField(
            model_name='tenantuser',
            old_name='created_at',
            new_name='joined_at',
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for URL routing', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Africa/Accra', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('VIEWER', 'Viewer')], default='STAFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core_tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='tenantuser',
            table='core_tenant_user',
        ),
        migrations.RemoveField(
            model_name='tenantuser',
            name='updated_at',
        ),
    ]
