# Generated by Django 5.2.15 on 2026-08-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0006_finalize_tenantuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/logos/'),
        ),
    ]
