# Generated by Django 5.2.15 on 2026-08-31 21:53

import django.db.models.deletion
from django.db import migrations, models


def create_default_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('core_tenant', 'SubscriptionPlan')
    SubscriptionPlan.objects.get_or_create(
        code='starter',
        defaults={
            'name': 'Starter',
            'description': 'For small farms getting started with basic farm management.',
            'amount': 0.00,
            'billing_cycle': 'monthly',
            'max_users': 5,
            'max_branches': 1,
            'features': ['dashboard', 'inventory', 'feed', 'basic_reports'],
            'is_active': True,
        },
    )
    SubscriptionPlan.objects.get_or_create(
        code='business',
        defaults={
            'name': 'Business',
            'description': 'For growing farms that need deeper operational coverage.',
            'amount': 150.00,
            'billing_cycle': 'monthly',
            'max_users': 20,
            'max_branches': 5,
            'features': ['dashboard', 'inventory', 'feed', 'finance', 'reports', 'multi_branch'],
            'is_active': True,
        },
    )
    SubscriptionPlan.objects.get_or_create(
        code='enterprise',
        defaults={
            'name': 'Enterprise',
            'description': 'For large operations with advanced controls and custom support.',
            'amount': 350.00,
            'billing_cycle': 'monthly',
            'max_users': 100,
            'max_branches': 20,
            'features': ['dashboard', 'inventory', 'feed', 'finance', 'reports', 'multi_branch', 'custom_support'],
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0007_alter_tenant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_subscription_plan',
                'ordering': ['amount'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('pending_manual_payment', 'Pending Manual Payment'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='trial', help_text='Manual subscription lifecycle for SaaS billing.', max_length=30),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('pending_manual_payment', 'Pending Manual Payment'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='trial', max_length=30)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscriptions', to='core_tenant.subscriptionplan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core_tenant.tenant')),
            ],
            options={
                'db_table': 'core_tenant_subscription',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RunPython(create_default_plans, reverse_code=migrations.RunPython.noop),
    ]
