# Generated by Django 5.2.15 on 2026-09-18 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0008_subscriptionplan_tenant_subscription_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('trial', 'Trial'), ('active', 'Active'), ('pending_manual_payment', 'Pending Manual Payment'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], max_length=30, null=True)),
                ('new_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('pending_manual_payment', 'Pending Manual Payment'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], max_length=30)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_history_updates', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core_tenant.tenantsubscription')),
            ],
            options={
                'db_table': 'core_subscription_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
