# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('organization_branch', '0001_initial'),
        ('organization_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiosecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('incident_date', models.DateField()),
                ('incident_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('corrective_action', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_branch.branch')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_house.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Biosecurity Incident',
                'verbose_name_plural': 'Biosecurity Incidents',
                'db_table': 'health_biosecurityincident',
                'indexes': [models.Index(fields=['tenant', 'branch', 'incident_date'], name='idx_biosec_tenant_branch_date'), models.Index(fields=['tenant', 'resolved'], name='idx_biosec_tenant_resolved')],
            },
        ),
    ]
