# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('bird_type', models.CharField(choices=[('layer', 'Layer'), ('broiler', 'Broiler')], max_length=20)),
                ('market_age_days', models.IntegerField(default=42)),
                ('laying_start_days', models.IntegerField(blank=True, null=True)),
                ('retirement_days', models.IntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'db_table': 'livestock_breed',
                'indexes': [models.Index(fields=['tenant', 'bird_type'], name='idx_breed_tenant_type')],
            },
        ),
    ]
