# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('health_outbreak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('outbreak', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health_outbreak.diseaseoutbreak')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Quarantine',
                'verbose_name_plural': 'Quarantines',
                'db_table': 'health_quarantine',
                'indexes': [models.Index(fields=['tenant', 'outbreak'], name='idx_quarantine_tenant_outbreak')],
            },
        ),
    ]
