# Generated by Django 5.2.15 on 2026-07-05 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0001_initial'),
        ('livestock_batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchVaccinationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock_batch.birdbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Batch Vaccination Plan',
                'verbose_name_plural': 'Batch Vaccination Plans',
                'db_table': 'health_batchvaccinationplan',
            },
        ),
        migrations.CreateModel(
            name='VaccinationProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('bird_type', models.CharField(max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Vaccination Program',
                'verbose_name_plural': 'Vaccination Programs',
                'db_table': 'health_vaccinationprogram',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_administered', models.DateField()),
                ('quantity_used', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock_batch.birdbatch')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_vaccination.batchvaccinationplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'db_table': 'health_vaccinationrecord',
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('recommended_day', models.IntegerField()),
                ('route', models.CharField(blank=True, max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_vaccination.vaccinationprogram')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Vaccination Schedule',
                'verbose_name_plural': 'Vaccination Schedules',
                'db_table': 'health_vaccinationschedule',
            },
        ),
        migrations.AddField(
            model_name='batchvaccinationplan',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_vaccination.vaccinationschedule'),
        ),
        migrations.AddIndex(
            model_name='vaccinationprogram',
            index=models.Index(fields=['tenant', 'bird_type'], name='idx_vaccprog_tenant_birdtype'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['tenant', 'batch', 'date_administered'], name='idx_vaccrec_tenant_batch_date'),
        ),
        migrations.AddIndex(
            model_name='vaccinationschedule',
            index=models.Index(fields=['tenant', 'program'], name='idx_vaccsched_tenant_program'),
        ),
        migrations.AddIndex(
            model_name='batchvaccinationplan',
            index=models.Index(fields=['tenant', 'batch', 'due_date'], name='idx_batchvacc_tenant_batch_due'),
        ),
        migrations.AddIndex(
            model_name='batchvaccinationplan',
            index=models.Index(fields=['tenant', 'status'], name='idx_batchvacc_tenant_status'),
        ),
    ]
