# Generated by Django 5.2.15 on 2026-07-12 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('health_vaccination', '0002_batchvaccinationplan_created_by_and_more'),
        ('livestock_batch', '0003_birdbatch_created_by_birdbatch_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinationschedule',
            options={'ordering': ['recommended_day'], 'verbose_name': 'Vaccination Schedule', 'verbose_name_plural': 'Vaccination Schedules'},
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='vaccine_name',
        ),
        migrations.RemoveField(
            model_name='vaccinationschedule',
            name='vaccine_name',
        ),
        migrations.AddField(
            model_name='vaccinationprogram',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='route',
            field=models.CharField(choices=[('water', 'Water'), ('injection', 'Injection'), ('spray', 'Spray'), ('eye_drop', 'Eye Drop'), ('oral', 'Oral'), ('other', 'Other')], default='water', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='batchvaccinationplan',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_plans', to='livestock_batch.birdbatch'),
        ),
        migrations.AlterField(
            model_name='batchvaccinationplan',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_plans', to='health_vaccination.vaccinationschedule'),
        ),
        migrations.AlterField(
            model_name='vaccinationprogram',
            name='bird_type',
            field=models.CharField(choices=[('layer', 'Layer'), ('broiler', 'Broiler'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='livestock_batch.birdbatch'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='health_vaccination.batchvaccinationplan'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='quantity_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='health_vaccination.vaccinationprogram'),
        ),
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='recommended_day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='route',
            field=models.CharField(choices=[('water', 'Water'), ('injection', 'Injection'), ('spray', 'Spray'), ('eye_drop', 'Eye Drop'), ('oral', 'Oral'), ('other', 'Other')], default='water', max_length=50),
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('bird_type', models.CharField(choices=[('layer', 'Layer'), ('broiler', 'Broiler'), ('both', 'Both')], default='both', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'db_table': 'health_vaccine',
            },
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='health_vaccination.vaccine'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='health_vaccination.vaccine'),
        ),
        migrations.AddIndex(
            model_name='vaccine',
            index=models.Index(fields=['tenant', 'bird_type'], name='idx_vaccine_tenant_type'),
        ),
    ]
