# Generated by Django 5.2.15 on 2026-07-13 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_vaccination', '0003_alter_vaccinationschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='health_vaccination.vaccine'),
        ),
    ]
