# Generated by Django 5.2.15 on 2026-07-13 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_tenant', '0003_alter_tenantuser_options_and_more'),
        ('organization_branch', '0003_branch_created_by_branch_updated_by'),
        ('production_harvest', '0004_alter_harvest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('whole_chicken', 'Whole Chicken'), ('breast', 'Chicken Breast'), ('thigh', 'Chicken Thigh'), ('wing', 'Chicken Wing'), ('gizzard', 'Gizzard'), ('other', 'Other')], default='whole_chicken', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece')], max_length=10)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('inventory_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_inventory', to='organization_branch.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meat_inventory', to='production_harvest.harvest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_tenant.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_meat',
            },
        ),
    ]
