# Generated by Django 5.2.15 on 2026-07-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_meat', '0002_meatinventory_unique_active_meat_inventory_per_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meatinventory',
            name='harvest',
        ),
    ]
